version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: shopfusion_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: shopfusion
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shopfusion_network

  redis:
    image: redis:7-alpine
    container_name: shopfusion_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shopfusion_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shopfusion_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_URL: mongodb://mongodb:27017/ShopFusion-new
      REDIS_URL: redis://redis:6379
      FRONTEND_URL: http://localhost:5173
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRE: ${JWT_EXPIRE}
      EXPIRE_COOKIE: ${EXPIRE_COOKIE}
      SMTP_SERVICE: ${SMTP_SERVICE}
      SMTP_MAIL: ${SMTP_MAIL}
      SMTP_PASS: ${SMTP_PASS}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
    depends_on:
      - mongodb
      - redis
    networks:
      - shopfusion_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shopfusion_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_SERVER_URL: http://localhost:3000
    depends_on:
      - backend
    networks:
      - shopfusion_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
  redis_data:

networks:
  shopfusion_network:
    driver: bridge